[2022-05-08 03:41:14,942] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-05-08 03:41:14,972] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-05-08 03:41:14,973] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 03:41:14,974] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-08 03:41:14,976] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-08 03:41:15,017] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_data> on 2022-05-01 00:00:00+00:00
[2022-05-08 03:41:15,031] {standard_task_runner.py:52} INFO - Started process 24858 to run task
[2022-05-08 03:41:15,059] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_script', 'extract_data', 'scheduled__2022-05-01T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/ETL_script.py', '--cfg-path', '/tmp/tmp6waqq5n9', '--error-file', '/tmp/tmp03vkiadw']
[2022-05-08 03:41:15,061] {standard_task_runner.py:80} INFO - Job 140: Subtask extract_data
[2022-05-08 03:41:15,189] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_script.extract_data scheduled__2022-05-01T00:00:00+00:00 [running]> on host 4c9d01f48299
[2022-05-08 03:41:15,507] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_script
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-01T00:00:00+00:00
[2022-05-08 03:41:15,517] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-08 03:41:15,527] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/API_extract.py']
[2022-05-08 03:41:15,607] {subprocess.py:85} INFO - Output:
[2022-05-08 03:41:15,637] {subprocess.py:89} INFO - bash: /Users/hamza.ahmed/Coding: No such file or directory
[2022-05-08 03:41:15,640] {subprocess.py:93} INFO - Command exited with return code 127
[2022-05-08 03:41:15,678] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-08 03:41:15,714] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_script, task_id=extract_data, execution_date=20220501T000000, start_date=20220508T034114, end_date=20220508T034115
[2022-05-08 03:41:15,762] {standard_task_runner.py:98} ERROR - Failed to execute job 140 for task extract_data (Bash command failed. The command returned a non-zero exit code 127.; 24858)
[2022-05-08 03:41:15,795] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-08 03:41:15,898] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
