[2022-04-30 23:27:08,794] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-04-30 23:27:08,804] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-04-30 23:27:08,805] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 23:27:08,806] {taskinstance.py:1250} INFO - Starting attempt 1 of 6
[2022-04-30 23:27:08,807] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-30 23:27:08,819] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_podsight_data> on 2022-04-17 00:00:00+00:00
[2022-04-30 23:27:08,823] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2022-04-30 23:27:08,826] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podsight_ETL', 'extract_podsight_data', 'scheduled__2022-04-17T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/podsight_ETL.py', '--cfg-path', '/tmp/tmph41e1v5w', '--error-file', '/tmp/tmpac3gb6p4']
[2022-04-30 23:27:08,827] {standard_task_runner.py:80} INFO - Job 15: Subtask extract_podsight_data
[2022-04-30 23:27:08,882] {logging_mixin.py:109} INFO - Running <TaskInstance: podsight_ETL.extract_podsight_data scheduled__2022-04-17T00:00:00+00:00 [running]> on host 4002ff4fcea6
[2022-04-30 23:27:08,939] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podsight_ETL
AIRFLOW_CTX_TASK_ID=extract_podsight_data
AIRFLOW_CTX_EXECUTION_DATE=2022-04-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-17T00:00:00+00:00
[2022-04-30 23:27:08,941] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-30 23:27:08,943] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 "/Users/hamza.ahmed/Coding Projects/Python_Apps/API Access/Podsights/podsight_API_JumpCloud.py"']
[2022-04-30 23:27:08,955] {subprocess.py:85} INFO - Output:
[2022-04-30 23:27:09,069] {subprocess.py:89} INFO - python3: can't open file '/Users/hamza.ahmed/Coding Projects/Python_Apps/API Access/Podsights/podsight_API_JumpCloud.py': [Errno 2] No such file or directory
[2022-04-30 23:27:09,073] {subprocess.py:93} INFO - Command exited with return code 2
[2022-04-30 23:27:09,090] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-04-30 23:27:09,105] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=podsight_ETL, task_id=extract_podsight_data, execution_date=20220417T000000, start_date=20220430T232708, end_date=20220430T232709
[2022-04-30 23:27:09,123] {standard_task_runner.py:98} ERROR - Failed to execute job 15 for task extract_podsight_data (Bash command failed. The command returned a non-zero exit code 2.; 92)
[2022-04-30 23:27:09,161] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-30 23:27:09,218] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
