[2022-05-01 17:26:16,364] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:18:11.529489+00:00 [queued]>
[2022-05-01 17:26:16,375] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:18:11.529489+00:00 [queued]>
[2022-05-01 17:26:16,376] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 17:26:16,377] {taskinstance.py:1250} INFO - Starting attempt 5 of 6
[2022-05-01 17:26:16,378] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 17:26:16,391] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_podsight_data> on 2022-05-01 17:18:11.529489+00:00
[2022-05-01 17:26:16,395] {standard_task_runner.py:52} INFO - Started process 532 to run task
[2022-05-01 17:26:16,399] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podsight_ETL', 'extract_podsight_data', 'manual__2022-05-01T17:18:11.529489+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/podsight_ETL.py', '--cfg-path', '/tmp/tmps4w22ikh', '--error-file', '/tmp/tmpylkclldv']
[2022-05-01 17:26:16,400] {standard_task_runner.py:80} INFO - Job 39: Subtask extract_podsight_data
[2022-05-01 17:26:16,457] {logging_mixin.py:109} INFO - Running <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:18:11.529489+00:00 [running]> on host ba3d3fc460bf
[2022-05-01 17:26:16,516] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hamza.ahmed@liquidagency.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podsight_ETL
AIRFLOW_CTX_TASK_ID=extract_podsight_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T17:18:11.529489+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-01T17:18:11.529489+00:00
[2022-05-01 17:26:16,518] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-01 17:26:16,520] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 "/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py"']
[2022-05-01 17:26:16,532] {subprocess.py:85} INFO - Output:
[2022-05-01 17:26:16,627] {subprocess.py:89} INFO - python3: can't open file '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py': [Errno 2] No such file or directory
[2022-05-01 17:26:16,631] {subprocess.py:93} INFO - Command exited with return code 2
[2022-05-01 17:26:16,646] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-05-01 17:26:16,653] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=podsight_ETL, task_id=extract_podsight_data, execution_date=20220501T171811, start_date=20220501T172616, end_date=20220501T172616
[2022-05-01 17:26:16,675] {standard_task_runner.py:98} ERROR - Failed to execute job 39 for task extract_podsight_data (Bash command failed. The command returned a non-zero exit code 2.; 532)
[2022-05-01 17:26:16,695] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-01 17:26:16,749] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
